spring:
  application:
    name: spring-ai-ollama-a

  ai:
    ollama:
      base-url: http://localhost:11434

      chat:
        model: openchat:latest

      embedding:
        options:
          model: nomic-embed-text

logging:
  level:
    org.springframework.ai.chat.client: DEBUG